create table if not exists tasks (
    id bigint generated by default as identity primary key,
    title varchar(100) not null,
    description varchar(2000),
    status varchar(20) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create index if not exists idx_tasks_status on tasks(status);
create index if not exists idx_tasks_created_at on tasks(created_at desc);
